apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcl-guestbook-ui
  labels:
    app: kcl-guestbook-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcl-guestbook-ui
  template:
    metadata:
      labels:
        app: kcl-guestbook-ui
    spec:
      containers:
      - guestbook: guestbook
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - protocol: TCP
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kcl-guestbook-ui
  labels:
    app: kcl-guestbook-ui
spec:
  type: LoadBalancer
  selector:
    app: kcl-guestbook-ui
  ports:
  - port: 80
    protocol: TCP
