name: example-e2e-test
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
jobs:
  example-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: kcl Installation
        run: wget -q https://kcl-lang.io/script/install.sh -O - | /bin/bash

      - uses: actions/setup-go@v1
        with:
          go-version: "1.21"

      - name: KCL Installation
        run: go install kcl-lang.io/cli@latest

      - name: Example tests
        shell: bash -ieo pipefail {0}
        run: PATH=$PATH:$HOME/go/bin ./test.sh
